/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthInviteRouteImport } from './routes/auth/invite'
import { Route as DashboardVolumesRouteImport } from './routes/_dashboard/volumes'
import { Route as DashboardTraefikRouteImport } from './routes/_dashboard/traefik'
import { Route as DashboardTeamRouteImport } from './routes/_dashboard/team'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardResourcesRouteImport } from './routes/_dashboard/resources'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard/projects'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardDeploymentsRouteImport } from './routes/_dashboard/deployments'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCronjobsRouteImport } from './routes/_dashboard/cronjobs'
import { Route as DashboardClusterRouteImport } from './routes/_dashboard/cluster'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard/apps'
import { Route as DashboardProjectsIdRouteImport } from './routes/_dashboard/projects_/$id'
import { Route as DashboardProjectsIdIndexRouteImport } from './routes/_dashboard/projects_/$id/index'
import { Route as DashboardProjectsIdDatabasesDbIdRouteImport } from './routes/_dashboard/projects_/$id/databases.$dbId'
import { Route as DashboardProjectsIdAppsAppIdRouteImport } from './routes/_dashboard/projects_/$id/apps.$appId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVolumesRoute = DashboardVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTraefikRoute = DashboardTraefikRouteImport.update({
  id: '/traefik',
  path: '/traefik',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCronjobsRoute = DashboardCronjobsRouteImport.update({
  id: '/cronjobs',
  path: '/cronjobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClusterRoute = DashboardClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdIndexRoute =
  DashboardProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdDatabasesDbIdRoute =
  DashboardProjectsIdDatabasesDbIdRouteImport.update({
    id: '/databases/$dbId',
    path: '/databases/$dbId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)
const DashboardProjectsIdAppsAppIdRoute =
  DashboardProjectsIdAppsAppIdRouteImport.update({
    id: '/apps/$appId',
    path: '/apps/$appId',
    getParentRoute: () => DashboardProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof DashboardAppsRoute
  '/cluster': typeof DashboardClusterRoute
  '/cronjobs': typeof DashboardCronjobsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRoute
  '/resources': typeof DashboardResourcesRoute
  '/settings': typeof DashboardSettingsRoute
  '/team': typeof DashboardTeamRoute
  '/traefik': typeof DashboardTraefikRoute
  '/volumes': typeof DashboardVolumesRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/projects/$id': typeof DashboardProjectsIdRouteWithChildren
  '/projects/$id/': typeof DashboardProjectsIdIndexRoute
  '/projects/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/projects/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof DashboardAppsRoute
  '/cluster': typeof DashboardClusterRoute
  '/cronjobs': typeof DashboardCronjobsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRoute
  '/resources': typeof DashboardResourcesRoute
  '/settings': typeof DashboardSettingsRoute
  '/team': typeof DashboardTeamRoute
  '/traefik': typeof DashboardTraefikRoute
  '/volumes': typeof DashboardVolumesRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/projects/$id': typeof DashboardProjectsIdIndexRoute
  '/projects/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/projects/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/apps': typeof DashboardAppsRoute
  '/_dashboard/cluster': typeof DashboardClusterRoute
  '/_dashboard/cronjobs': typeof DashboardCronjobsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deployments': typeof DashboardDeploymentsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/projects': typeof DashboardProjectsRoute
  '/_dashboard/resources': typeof DashboardResourcesRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/team': typeof DashboardTeamRoute
  '/_dashboard/traefik': typeof DashboardTraefikRoute
  '/_dashboard/volumes': typeof DashboardVolumesRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_dashboard/projects_/$id': typeof DashboardProjectsIdRouteWithChildren
  '/_dashboard/projects_/$id/': typeof DashboardProjectsIdIndexRoute
  '/_dashboard/projects_/$id/apps/$appId': typeof DashboardProjectsIdAppsAppIdRoute
  '/_dashboard/projects_/$id/databases/$dbId': typeof DashboardProjectsIdDatabasesDbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/cluster'
    | '/cronjobs'
    | '/dashboard'
    | '/deployments'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/settings'
    | '/team'
    | '/traefik'
    | '/volumes'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/projects/$id'
    | '/projects/$id/'
    | '/projects/$id/apps/$appId'
    | '/projects/$id/databases/$dbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/cluster'
    | '/cronjobs'
    | '/dashboard'
    | '/deployments'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/settings'
    | '/team'
    | '/traefik'
    | '/volumes'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/projects/$id'
    | '/projects/$id/apps/$appId'
    | '/projects/$id/databases/$dbId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/apps'
    | '/_dashboard/cluster'
    | '/_dashboard/cronjobs'
    | '/_dashboard/dashboard'
    | '/_dashboard/deployments'
    | '/_dashboard/profile'
    | '/_dashboard/projects'
    | '/_dashboard/resources'
    | '/_dashboard/settings'
    | '/_dashboard/team'
    | '/_dashboard/traefik'
    | '/_dashboard/volumes'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/register'
    | '/_dashboard/projects_/$id'
    | '/_dashboard/projects_/$id/'
    | '/_dashboard/projects_/$id/apps/$appId'
    | '/_dashboard/projects_/$id/databases/$dbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/volumes': {
      id: '/_dashboard/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof DashboardVolumesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/traefik': {
      id: '/_dashboard/traefik'
      path: '/traefik'
      fullPath: '/traefik'
      preLoaderRoute: typeof DashboardTraefikRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/team': {
      id: '/_dashboard/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resources': {
      id: '/_dashboard/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deployments': {
      id: '/_dashboard/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cronjobs': {
      id: '/_dashboard/cronjobs'
      path: '/cronjobs'
      fullPath: '/cronjobs'
      preLoaderRoute: typeof DashboardCronjobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cluster': {
      id: '/_dashboard/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof DashboardClusterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects_/$id': {
      id: '/_dashboard/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects_/$id/': {
      id: '/_dashboard/projects_/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof DashboardProjectsIdIndexRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/databases/$dbId': {
      id: '/_dashboard/projects_/$id/databases/$dbId'
      path: '/databases/$dbId'
      fullPath: '/projects/$id/databases/$dbId'
      preLoaderRoute: typeof DashboardProjectsIdDatabasesDbIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
    '/_dashboard/projects_/$id/apps/$appId': {
      id: '/_dashboard/projects_/$id/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/projects/$id/apps/$appId'
      preLoaderRoute: typeof DashboardProjectsIdAppsAppIdRouteImport
      parentRoute: typeof DashboardProjectsIdRoute
    }
  }
}

interface DashboardProjectsIdRouteChildren {
  DashboardProjectsIdIndexRoute: typeof DashboardProjectsIdIndexRoute
  DashboardProjectsIdAppsAppIdRoute: typeof DashboardProjectsIdAppsAppIdRoute
  DashboardProjectsIdDatabasesDbIdRoute: typeof DashboardProjectsIdDatabasesDbIdRoute
}

const DashboardProjectsIdRouteChildren: DashboardProjectsIdRouteChildren = {
  DashboardProjectsIdIndexRoute: DashboardProjectsIdIndexRoute,
  DashboardProjectsIdAppsAppIdRoute: DashboardProjectsIdAppsAppIdRoute,
  DashboardProjectsIdDatabasesDbIdRoute: DashboardProjectsIdDatabasesDbIdRoute,
}

const DashboardProjectsIdRouteWithChildren =
  DashboardProjectsIdRoute._addFileChildren(DashboardProjectsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardClusterRoute: typeof DashboardClusterRoute
  DashboardCronjobsRoute: typeof DashboardCronjobsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTraefikRoute: typeof DashboardTraefikRoute
  DashboardVolumesRoute: typeof DashboardVolumesRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardClusterRoute: DashboardClusterRoute,
  DashboardCronjobsRoute: DashboardCronjobsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTraefikRoute: DashboardTraefikRoute,
  DashboardVolumesRoute: DashboardVolumesRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
